### ISSUE TITLE
possible ArcMap 10.6 issue?

### ISSUE THREAD

**Issue by giswgjs** [fitnr/mxd2qgs#2]
Thanks for this important and promising tool!
We just try to check this out with ArcMap 10.6 and ran into some issues:
1) After selecting the outfile name and starting the tool, we got a traceback
```    
Traceback (most recent call last):
      File "C:\tmp\mxd2qgs-master\mxd2qgs_arc_script.py", line 27, in <module>
        converter.convert(outfile)
    TypeError: convert() takes exactly 1 argument (2 given)
```
Which is clear, because `convert` gets as arguments `self` and `outfile`, but is only defined by `def convert(self):...` expecting `self` as the only argument.

2) Tried changing `converter.convert(outfile)` to `converter.convert()` in the above referenced `line 27` solved 1) for the moment but then got another traceback of which we think it might be related to the ArcGIS version (10.6):
```
    Traceback (most recent call last):
      File "C:\tmp\mxd2qgs-master\mxd2qgs_arc_script.py", line 27, in <module>
        converter.convert()
      File "C:\tmp\mxd2qgs-master\mxd2qgs.py", line 72, in convert
        layers = self.layers()
      File "C:\tmp\mxd2qgs-master\mxd2qgs.py", line 313, in layers
        singlesymbol.appendChild(symbol)
      File "C:\Python27\ArcGIS10.6\Lib\xml\dom\minidom.py", line 113, in appendChild
        if node.nodeType == self.DOCUMENT_FRAGMENT_NODE:
    AttributeError: 'NoneType' object has no attribute 'nodeType'
```
We tried this with a very simple symbology, only one single layer with Features/Single symbol rsp. Categories/Unique values symbology.

Any ideas about this are greatly appreciated!

**Comment by fitnr** [comment]
Promising is a good word. I haven't looked at this repo in a long time and it should be regarding as a rough starting point for creating a converter, rather than anything close to a functional tool. Since the last time I looked, there have been at one new version of ArcMap and several updates of QGIS, so good luck!
